import * as Form from '@radix-ui/react-form';
import { ChangeEvent, ComponentPropsWithoutRef } from 'react';
import { cn } from '@/lib/cn';
import { useFormState, useFormTheme } from '../../context/formContext';
import { composeHandlers } from '../../helpers/composeHandlers';
import { getControlId, getMessageId } from '../../helpers/ids';
import { useValidationFlowStatus } from '../../helpers/state';
import { SharedControlProps } from '../../helpers/types';
import { useUncontrolValidationHandlers } from './useUncontrolValidationHandlers';

//~See below for explanation
export type InputControlProps =
  Omit<ComponentPropsWithoutRef<'input'>, 'onFocus' | 'onBlur' | 'onInvalid' | 'onChange'> &
  SharedControlProps & {
    onChange?: (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  };

export function BaseInputControl({
  className,
  name,
  type,
  onFocus,
  onBlur,
  onChange,
  onInvalid,
  'aria-describedby': ariaDescribedBy, //*See below for explanation
  id,
  ...props
}: InputControlProps & { type: ComponentPropsWithoutRef<'input'>['type'] }) {
  const { classes } = useFormTheme();
  const { formId, errors } = useFormState();
  const fieldState = useValidationFlowStatus(name);
  const handlers = useUncontrolValidationHandlers(name);
  const messageId = getMessageId(formId, name);

  return (
    <Form.Control asChild>
      <input
        {...props}
        id={id ?? getControlId(formId, name)}
        className={cn(classes?.control, className)}
        data-validation={fieldState}
        type={type}
        name={name}
        aria-describedby={ariaDescribedBy ?? messageId}
        aria-invalid={errors[name] ? true : undefined}
        onFocus={composeHandlers(handlers.onFocus, onFocus)}
        onBlur={composeHandlers(handlers.onBlur, onBlur)}
        onChange={composeHandlers(handlers.onChange, onChange)}
        onInvalid={composeHandlers(handlers.onInvalid, onInvalid)}
      />
    </Form.Control>
  );
}

/*
~Omit onFocus, onBlur, and onInvalid from the native input props since we're handling those
internally for validation purposes. Let's see the issue cause without Omit:

1) Native input prop (from ComponentPropsWithoutRef<'input'>):
onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;

2) Your re‑declared union handler (if you add it without Omit):
onFocus?: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;

3) When those two appear together on the same type (object intersection), TypeScript computes the
property type as the intersection of the two function types:
(e: FocusEvent<HTMLInputElement>) => void & (e: FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void

4) For parameters that means the parameter type becomes the intersection of the two event types:
FocusEvent<HTMLInputElement> & FocusEvent<HTMLInputElement | HTMLTextAreaElement>

That intersection effectively requires currentTarget to be an HTMLInputElement and also a member of
the union — which simplifies to FocusEvent<HTMLInputElement> (i.e., the input‑only event). The
compiler therefore narrows the handler to the input case.
*/

/*
*We want to allow users to override the aria-describedby if they want, but by default it should point
to the message element for this control. The message element will have an id of
`${formId}-${fieldName}-message` which is generated by getMessageId.
Here we use a string in the destructoring because of its hyphen and rename it to the camel case
ariaDescribedBy for use in the component. If the user doesn't provide an aria-describedby, we'll use
the messageId.
*/
